name: 手动抓取

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run start.sh
        run: |
          python ./csdn_crawler.py ${{ secrets.PUSH_TOKEN }}
